language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
before_script: npm test
script: npm run deploy
env:
  global:
  - secure: mZMbZlq3h56RI2BcmNOm6bKnfX4hwXY5n4bjGCD3LLFoylYc7MDyTHRJQ+F9aQr9WsxIYYkskMK20+9BCU+hx1li4FjVPgMd76qv4IlZiuAchzxs5JRVDCCJPM/DPEUD7Gfjz6jXvKrYbmfehW0+efJI1DdXpJGg3tYRiXvORWcBdk1AlOnKCTi4qEYkV7RMU2S3RS34tBTbJoEgKObZfRIDYzHCo2D6G5+NlrOwIfDYPWfcfFCbeNrstOe3rn2haUmxyN3WS4JcFKBtZUUUWozNlkuZV9kAsLx0pFJSUe92vEcCoHuglyG5bhFiTtJVpgKtkFqKGKKAUNTwNt+jtppYOucSiKTwMA4V6dxQro0/4URl41fLLeXSOEj2pM6t0wd4wvPlfrMWeZt4lOPT3AWn7KcX3VuNr44wNNUMjTy8sOV/+Jtj1kdcytlaw4fth2GwFBjd7pLC2K0wVzjWzfLhXmtsXqSfxsblhjmyYNH9HZJ2g5hB9dKUNVye9mdl5VWrgx7n/GLw/ewadd2U9EXTJR4Kf9Dw1mnhihtSQn890aAOBtDIHqsWK2zyNoOpVra+drJ2yzADR6oSQ+6U8k2Zg7hWTOAhKx7SxzSH+ISpDYsBJeeEGanV0Pif4bkUGJEm0lyXxsTUeT7MZNTGDWYBY+10QZGg38I/DDYTonE=
  - secure: PW/WbyYkkrEo1HoP1pwyFljFFyVft8BGJOAfINQBwdlvoO3+ceTOvNEgN9HvvYD/Ryd0rNFQnygA0VvcgV/IW8hXmSe9frzR3ZkVc3alG9a6PVGsfhwD1iKltRt45D9HCpAIKHKZYCuHOfTrdjR/cDT0miLKgNvZ3PvhZk/6zdlzu1E4T/9brDsYwN4tiHJX5R0f7lk5ma5ZDk+vqbE3wMj/NzjtZadopzF5MV6oG+1a6OS/kdAqHvPOvfeg5LSdiWGE3f8a9DVdTypDyoAyKG5qCXmugEvPgQokSw2u0iZqPToVHLH9hUoA0Rug4FbY6lEHyIrQER2+cwjuSVonPBJvuD39aaWM5YTgCqVX+MyKkSj6uOacFk1+06eFv+H6aV3wDpb5el+SceXC4LwPzPXOPASzd8EDdDAfq+V9EynHrcmzCsyLGSEIL2r7zrJWWtXxVk3lB4xCO9lO/z26hcRlDBAQkiG3CY0j8pGxzyoQrhVAXKXvU5IvtXbwo0gUqCfUwCKqUPR+/rioL+eKvzXDvs7Y0B38fSmaYq7neezi3ojokP1bjjEEXvmDaWp79TQoLKMTJJG5itNjiJEt42b/K0hYOke61cHXA4JaOqdYg0Jn2syoVWjkMrs4B+E2Q1cqfph+bwcOp/WfPZ0iOdufO/gOo7xyp7dPHEIiEDk=
